---
 - name: "open port"
   firewalld:
           port: 80/tcp
           permanent: yes
           state: enabled
 - name: "restart service"
   service:
           name: firewalld
           state: restarted
